pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t genai-app .'
            }
        }

        stage('Deploy') {
            steps {
                sh 'kubectl apply -f kubernetes/'
            }
        }
    }
}
